Comment test.bs
Comment This is an example of a basic program
Comment
Comment This form of basic is interpreted, not compiled

Function Main
Begin
	PrintLine "Hello!"
	PrintLine "Welcome to Basic!!"
	
	Call FuncTest
	Call FuncTest2
	
	Call MathTest
	
	Exit
End

Function FuncTest
Begin
	PrintLine "This is a function!"	
End

Function FuncTest2
Begin
	PrintLine "Function test 2"
End

Function MathTest
Begin
	Var no1
	Var no2
	Var no3
	
	Define no1 as 10
	Define no2 as 20
	
	Add no1 and no2
	Set no3
	
	PrintLine no3
End

Call Main
