Comment test.bs
Comment This is an example of a basic program
Comment
Comment This form of basic is interpreted, not compiled

Function Main
Begin
	Print "Hello!"
	Print "Welcome to Basic!!"
	
	Call FuncTest
	Call FuncTest2
	
	Call MathTest
	
	Exit
End

Function FuncTest
Begin
	Print "This is a function!"	
End

Function FuncTest2
Begin
	Print "Function test 2"
End

Function MathTest
Begin
	Var no1
	Var no2
	
	Define no1 as 10
	Define no2 as 20
	
	Print no1
	Print no2
End

Call Main
