Comment params.bs
Comment This tests command line parameters

Function Param2[str]
Begin
	Print "The awesome string: "
	Print str
	PrintLine ""
End

Function SayHello
Begin
	PrintLine "Hello!"
End

Function Param[str1,str2]
Begin
	Print "Str1: "
	Print str1
	PrintLine ""
	
	Print "Str2: "
	Print str2
	PrintLine ""
	
	Call Param2[str1]
	Call SayHello
End

Var msg1
Define msg1 as "Hello!"

Call Param[msg1,"I am awesome!!"]
